import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/store/providers";
import AuthGuard from "@/components/common/AuthGaurd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Abel } from "next/font/google";

const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abel",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={abel.className}
      >
        <Providers><AuthGuard>{children}</AuthGuard></Providers>
      </body>
    </html>
  );
}
